attributes:
  trl:
    ontology_class: TRL
    category_class: SimpleValueAttribute
    dtype: int
    aliases:
      - Technology Readiness Level

  tech_maturity:
    ontology_class: tech_maturity
    category_class: CategoricalAttribute
    dtype: text
    aliases:
      - Technology Maturity

  technical_efficiency:
    ontology_class: technical_efficiency
    category_class: PhysicalAttribute
    dtype: decimal
    aliases:
      - Technical Efficiency

  theoretical_efficiency:
    ontology_class: theoretical_efficiency
    category_class: PhysicalAttribute
    dtype: decimal
    aliases:
      - Theoretical Efficiency

  operating_temperature_c:
    ontology_class: operating_temperature_c
    category_class: PhysicalAttribute
    dtype: decimal
    aliases:
      - Operating Temperature

  lifetime_yr:
    ontology_class: Lifetime
    category_class: PhysicalAttribute
    dtype: decimal
    aliases:
      - Economic Lifetime
      - EconomicLifetime

  capex_one_time:
    ontology_class: CAPEX
    category_class: SimpleCostAttribute
    dtype: decimal
    aliases:
      - Capital Expenditure One Time

  capex_per_capacity:
    ontology_class: CAPEXPerCapacity
    category_class: UnitBasedCostAttribute
    dtype: decimal
    aliases:
      - Capital Expenditure Per Capacity
      - Capex Per Capacity

  opex_one_time:
    ontology_class: OPEX
    category_class: SimpleCostAttribute
    dtype: decimal
    aliases:
      - One-Time Operational Expenditure
      - Opex One-Time

  opex_fix_pct_of_capex:
    ontology_class: opex_fix_pct_of_capex
    category_class: PhysicalAttribute
    dtype: decimal
    aliases:
      - Fixed Operational Expenditure Percentage Of Capital Expenditure

  opex_per_capacity_yr:
    ontology_class: OPEXPerCapacity
    uri_segment: OPEX_power
    category_class: UnitBasedCostAttribute
    dtype: decimal
    aliases:
      - Annual OPEX Per Capacity
      - Annual Operational Expenditure Per Installed Capacity
      - Operational Expenditure Per Capacity

  opex_per_energy:
    ontology_class: OPEX_energy
    category_class: UnitBasedCostAttribute
    dtype: decimal
    aliases:
      - Operational Expenditure Per Energy
      - Operating Expenditure Per Energy

  min_installation_size:
    ontology_class: min_installation_size
    category_class: PhysicalAttribute
    dtype: decimal
    aliases:
      - Minimum Installation Size

  uncertainty_rating:
    ontology_class: uncertainty_rating
    category_class: CategoricalAttribute
    dtype: text
    aliases:
      - Uncertainty Rating

  discount_rate_pct:
    ontology_class: InterestRate
    category_class: PhysicalAttribute
    dtype: decimal
    aliases:
      - Discount Rate

  reference_unit_size:
    ontology_class: reference_unit_size
    category_class: PhysicalAttribute
    dtype: decimal
    aliases:
      - Reference Unit Size
